/**
 * ValuePickr Tool
 *
 * Searches and fetches investment theses from ValuePickr forum.
 * Returns comprehensive summaries of the original thesis and recent sentiment,
 * generated by a cheaper model (Gemini 2.5 Flash) to provide full context.
 *
 * This is the PRIMARY source for buy/sell decisions - we're dealing with real money,
 * so the agent needs complete, diligent research.
 */

import { registerToolExecutor, type ToolResponse } from "./registry";
import { ValuePickrService } from "../scrapers/valuepickr";

interface GetStockThesisArgs {
  query: string;
}

/**
 * Get stock thesis from ValuePickr
 */
async function getStockThesis(
  args: Record<string, unknown>
): Promise<ToolResponse> {
  const { query } = args as unknown as GetStockThesisArgs;

  if (!query || query.trim().length === 0) {
    return {
      success: false,
      error: {
        code: "PARSE_ERROR",
        message: "Query parameter is required",
        retryable: false,
      },
    };
  }

  try {
    console.log(`[ValuePickr Tool] Researching: ${query}`);

    let intel = await ValuePickrService.getResearch(query.trim());

    // RETRY LOGIC: If not found, try stripping common suffixes or simplifying the name
    if (!intel) {
      // 1. Try cleaning suffixes
      const cleanQuery = query
        .replace(/\s+(Limited|Ltd|Corporation|Corp|Inc|Company|Co)\.?\s*$/i, "")
        .replace(/\s+and\s+/i, " ") // Housing and Urban -> Housing Urban
        .replace(/developmentoration/i, "Development") // Fix specific hallucination if persistent
        .trim();

      if (cleanQuery !== query.trim() && cleanQuery.length > 2) {
        console.log(`[ValuePickr Tool] Retry: "${query}" -> "${cleanQuery}"`);
        intel = await ValuePickrService.getResearch(cleanQuery);
      }
    }

    if (!intel) {
      return {
        success: true,
        data: {
          found: false,
          query: query,
          message: `No ValuePickr discussion found for "${query}". This stock may not have been discussed by the value investing community yet.`,
          recommendation:
            "Consider searching with the full company name if you used a symbol, or vice versa.",
        },
        meta: {
          source: "valuepickr",
        },
      };
    }

    return {
      success: true,
      data: {
        found: true,
        query: query,
        topic_title: intel.topic_title,
        topic_url: intel.topic_url,
        thesis_summary: intel.thesis_summary,
        recent_sentiment: intel.recent_sentiment_summary,
        last_activity: intel.last_activity,
        instructions:
          "This is your PRIMARY source for investment decisions. The thesis summary explains WHY to invest in this company. The recent sentiment shows how the community currently views it. Use this to determine if the investment story is still intact before checking technicals.",
      },
      meta: {
        source: "valuepickr",
      },
    };
  } catch (error) {
    console.error("[ValuePickr Tool] Error:", error);

    const errorMessage =
      error instanceof Error ? error.message : "Unknown error";
    const isRateLimit =
      errorMessage.includes("429") ||
      errorMessage.includes("rate") ||
      errorMessage.includes("slow");

    return {
      success: false,
      error: {
        code: isRateLimit ? "RATE_LIMITED" : "UNKNOWN",
        message: errorMessage,
        retryable: isRateLimit,
      },
    };
  }
}

// Register the executor
registerToolExecutor("get_stock_thesis", getStockThesis);

export { getStockThesis };
